### PR TITLE
ENH: Allow applications use UTF-8 code page

### PR DESCRIPTION
**Pull request by lassoan**
If SlicerExecutionModel_USE_UTF8 is OFF (this is the default, for backward compatibility) then standard Windows API calls expects strings to be stored in the ANSI code page configured on the system.

If SlicerExecutionModel_USE_UTF8 is ON then all std::string or char buffers are expected to contain UTF-8 encoded string. This is what was the default on Mac OSX and Linux and starting from Windows Version 1903 (May 2019 Update) it has been made available as an option on Windows as well. This is where VTK and ITK (and most other software libraries) are moving towards, too.

### CODE REVIEW

**Comment by jcfr** [comment]
When building with `SlicerExecutionModel_USE_UTF8` set fo `OFF`, the test `Parser1Test3` is failing on windows (see below). That said, this is not related to this PR.


```
    Start 3: Parser1Test3

3: Test command: D:\T\SlicerExecutionModel-build\ModuleDescriptionParser\bin\Release\Parser1Test.exe "D:/T/SlicerExecutionModel/ModuleDescriptionParser/Testing/TestData/ParserTest3.xml"
3: Test timeout computed to be: 1500
3: unclosed token at line 39
1/1 Test #3: Parser1Test3 .....................***Failed    0.02 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.03 sec

The following tests FAILED:
          3 - Parser1Test3 (Failed)
Errors while running CTest
```

**Comment by jcfr** [comment]
Building reports the following warnings:

```
D:\T\SlicerExecutionModel\CMake\WindowsApplicationUseUtf8.manifest : manifest authoring warning 81010002: Unrecognized
Element "activeCodePage" in namespace "http://schemas.microsoft.com/SMI/2019/WindowsSettings". [D:\T\SlicerExecutionMod
el-build\GenerateCLP\GenerateCLPLauncher.vcxproj]
```

**Comment by jcfr** [comment]
And the test `GenerateCLPTest-Utf8Example-Test` is failing with `SlicerExecutionModel_USE_UTF8` set to `ON`

```
    Start 18: GenerateCLPTest-Utf8Example-Test

18: Test command: C:\cmake-3.15.2\bin\cmake.exe "-DTEST_SOURCE_DIR:PATH=D:/T/SlicerExecutionModel/GenerateCLP/Testing/Utf8Example" "-DTEST_BINARY_DIR:PATH=D:/T/SlicerExecutionModel-build/GenerateCLP/Testing/Utf8Example" "-DTEST_CONFIGURATION:STRING=Release" "-P" "D:/T/SlicerExecutionModel/GenerateCLP/Testing/CMake/GenerateCLPTest-Test.cmake"
18: Test timeout computed to be: 1500
18: Errors while running CTest
18: Test project D:/T/SlicerExecutionModel-build/GenerateCLP/Testing/Utf8Example
18:     Start 1: SlicerCLPExample1
18: 1/2 Test #1: SlicerCLPExample1 ................   Passed    0.01 sec
18:     Start 2: SlicerCLPExample2
18: 2/2 Test #2: SlicerCLPExample2 ................***Failed    0.02 sec
18:
18: 50% tests passed, 1 tests failed out of 2
18:
18: Total Test time (real) =   0.04 sec
18:
18: The following tests FAILED:
18:       2 - SlicerCLPExample2 (Failed)
18:
18: CMake Error at D:/T/SlicerExecutionModel/GenerateCLP/Testing/CMake/GenerateCLPTest-Test.cmake:25 (message):
18:   Failed to run Test:
18:
18:   Test project
18:   D:/T/SlicerExecutionModel-build/GenerateCLP/Testing/Utf8Example
18:
18:       Start 1: SlicerCLPExample1
18:
18:   1/2 Test #1: SlicerCLPExample1 ................  Passed 0.01 sec
18:
18:       Start 2: SlicerCLPExample2
18:
18:   2/2 Test #2: SlicerCLPExample2 ................***Failed 0.02 sec
18:
18:
18:
18:   50% tests passed, 1 tests failed out of 2
18:
18:
18:
18:   Total Test time (real) = 0.04 sec
18:
18:
18:
18:   The following tests FAILED:
18:
18:      2 - SlicerCLPExample2 (Failed)
18:
18:
18:
1/1 Test #18: GenerateCLPTest-Utf8Example-Test ...***Failed    0.12 sec

0% tests passed, 1 tests failed out of 1

Label Time Summary:
GenerateCLP    =   0.12 sec*proc (1 test)

Total Test time (real) =   0.16 sec

The following tests FAILED:
         18 - GenerateCLPTest-Utf8Example-Test (Failed)
Errors while running CTest
```

**Comment by lassoan** [comment]
@jcfr thank you for testing this.

> D:\T\SlicerExecutionModel\CMake\WindowsApplicationUseUtf8.manifest : manifest authoring warning 81010002: Unrecognized
Element "activeCodePage" in namespace "http://schemas.microsoft.com/SMI/2019/WindowsSettings". [D:\T\SlicerExecutionMod
el-build\GenerateCLP\GenerateCLPLauncher.vcxproj]

This should be no problem, I guess it is due to using an old Windows SDK that does not know about this option yet.

> And the test GenerateCLPTest-Utf8Example-Test is failing with SlicerExecutionModel_USE_UTF8 set to ON

Could you run the test with -VV (or check in the test logs) to see what the error message is?

It would be also nice if you could upgrade CMake so that circleci can execute tests.

**Comment by sjh26** [comment]
CTest doesn't capture that output, but running the test directly gives this:

inputStringEnum: Hungarian: árvíztűrő tükörfúrógép
inputFile: input-test-日本-árvíztűrő-tükörfúrógép.txt
outputFile: output-test-日本-árvíztűrő-tükörfúrógép.txt
written and read inputStringEnum: Hungarian: árvíztűrő tükörfúrógép
Windows version: 10.0 build 18362
Active code page: 65001
Expected file does not exist: alpha(α).txt

**Comment by lassoan** [comment]
Thanks for the log, it was very useful. It turned out that the test error was due to a typo that I've fixed but somehow did not get into the pull request.

I think the only remaining finding is the `manifest authoring warning 81010002: Unrecognized
Element "activeCodePage" in namespace` warning but I think it should be no problem - most likely mt.exe in that Windows SDK is just too old for this.

**Comment by jcfr** [comment]
At the exception of `Parser1Test3`, tests now pass.

@lassoan Do you know what could be wrong with `Parser1Test3` ?  

```
D:\T\SlicerExecutionModel-build>c:\cmake-3.15.2\bin\ctest.exe -C Release
Test project D:/T/SlicerExecutionModel-build
      Start  1: Parser1Test1
 1/18 Test  #1: Parser1Test1 ................................   Passed    0.08 sec
      Start  2: Parser1Test2
 2/18 Test  #2: Parser1Test2 ................................   Passed    0.02 sec
      Start  3: Parser1Test3
 3/18 Test  #3: Parser1Test3 ................................***Failed    0.02 sec
      Start  4: ModuleDescriptionTest
 4/18 Test  #4: ModuleDescriptionTest .......................   Passed    0.05 sec
      Start  5: GenerateCLPTest-Slicer3Example-Configure
 5/18 Test  #5: GenerateCLPTest-Slicer3Example-Configure ....   Passed   10.62 sec
      Start  6: GenerateCLPTest-Slicer3Example-Build
 6/18 Test  #6: GenerateCLPTest-Slicer3Example-Build ........   Passed    3.75 sec
      Start  7: GenerateCLPTest-Slicer3Example-Test
 7/18 Test  #7: GenerateCLPTest-Slicer3Example-Test .........   Passed    0.22 sec
      Start  8: GenerateCLPTest-PointExample1-Configure
 8/18 Test  #8: GenerateCLPTest-PointExample1-Configure .....   Passed    9.12 sec
      Start  9: GenerateCLPTest-PointExample1-Build
 9/18 Test  #9: GenerateCLPTest-PointExample1-Build .........   Passed    3.65 sec
      Start 10: GenerateCLPTest-CLPExample1-Configure
10/18 Test #10: GenerateCLPTest-CLPExample1-Configure .......   Passed    9.26 sec
      Start 11: GenerateCLPTest-CLPExample1-Build
11/18 Test #11: GenerateCLPTest-CLPExample1-Build ...........   Passed    3.91 sec
      Start 12: GenerateCLPTest-CLPExample1-Test
12/18 Test #12: GenerateCLPTest-CLPExample1-Test ............   Passed    0.08 sec
      Start 13: GenerateCLPTest-CLPTestMultiple-Configure
13/18 Test #13: GenerateCLPTest-CLPTestMultiple-Configure ...   Passed    9.04 sec
      Start 14: GenerateCLPTest-CLPTestMultiple-Build
14/18 Test #14: GenerateCLPTest-CLPTestMultiple-Build .......   Passed    3.96 sec
      Start 15: GenerateCLPTest-CLPTestMultiple-Test
15/18 Test #15: GenerateCLPTest-CLPTestMultiple-Test ........   Passed    0.07 sec
      Start 16: GenerateCLPTest-Utf8Example-Configure
16/18 Test #16: GenerateCLPTest-Utf8Example-Configure .......   Passed   10.09 sec
      Start 17: GenerateCLPTest-Utf8Example-Build
17/18 Test #17: GenerateCLPTest-Utf8Example-Build ...........   Passed    3.81 sec
      Start 18: GenerateCLPTest-Utf8Example-Test
18/18 Test #18: GenerateCLPTest-Utf8Example-Test ............   Passed    0.21 sec

94% tests passed, 1 tests failed out of 18
```

**Comment by jcfr** [comment]
I am merging since the failure associated with `Parser1Test3` is not specific to this PR. It was failing before.

**Pull request merged**
