### PR TITLE
BUG: Fix ctest error on ITKExpat linking in GenerateCLP testing

### PR DESCRIPTION
**Pull request by LucasGandel**
ITKEXPAT is no longer used and has been replaced by ITKExpat which
is now included by setting the project's COMPONENTS. (work by
Hans Johnson in PR #48)

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks :+1: 

As soon as the testing infrastructure is setup, will integrate. 

Here a possible improved commit message:

```
 BUG: Fix link error related to ITKExpat when using ITK > v4.8.1

ITKEXPAT is no longer used and has been replaced by ITKExpat which
is now included by setting the project's COMPONENTS.
See InsightSoftwareConsortium/ITK@1234567

This commit integrates contribution by  Hans Johnson (See PR #48)

It fixes the following link error:

<TODO: Add example of link error>

```

Make sure to update : 
* `InsightSoftwareConsortium/ITK@1234567` with the correct commit reference.
* `<TODO: Add example of link error>`

**Comment by LucasGandel** [comment]
I agree for the improved commit message. Just a thing concerning Hans
Johnson work, I didn't integrate his change in my pull request. Mine is
fixing another bug due to ITKExpat linking.
Do you want me to add his file so we have only one PR that fixes ITKExpat
issues?

Thanks,
Lucas

2015-10-07 12:12 GMT-04:00 Jean-Christophe Fillion-Robin <
notifications@github.com>:

**Comment by hjmjohnson** [comment]
Lucas,

Please do commit my patch as well.

Thank you. 

Hans


From:  Lucas Gandel
Reply-To:  Slicer/SlicerExecutionModel
Date:  Thursday, October 8, 2015 at 3:13 PM
To:  Slicer/SlicerExecutionModel
Subject:  Re: [SlicerExecutionModel] BUG: Fix ctest error on ITKExpat linking in GenerateCLP testing (#51)

I agree for the improved commit message. Just a thing concerning Hans
Johnson work, I didn't integrate his change in my pull request. Mine is
fixing another bug due to ITKExpat linking.
Do you want me to add his file so we have only one PR that fixes ITKExpat
issues?

Thanks,
Lucas

2015-10-07 12:12 GMT-04:00 Jean-Christophe Fillion-Robin <
notifications@github.com>:

**Comment by thewtex** [comment]
+1 to this change. I ran into this the other day...

**Comment by jcfr** [comment]
@thewtex Could  you revert and update the commit message as suggested above ? This will trigger CircleCI  and give the green light to integrate. Thanks

**Comment by thewtex** [comment]
@jcfr Yes, will do.

**Comment by thewtex** [comment]
Pull request created in #60

**Pull request merged**
