### PR TITLE
ENH: Vendor SharedForward which was removed from KWSys

### LINKED ISSUE #138: KWSys / itksys no longer has a SharedForward.h.in file
ITK has updated its version of KWSys (the source of itksys).  

https://github.com/InsightSoftwareConsortium/ITK/commit/2c45eec4b39cd8b2a0a1b0dc2a6e4182b73bd91f

That update introduced a version of KWSys that does not contain the SharedForward.h.in file, as required by GenerateCLPLauncher.

https://github.com/Slicer/SlicerExecutionModel/blob/bd2efa9e70900483e6c26a54d7108d97bf36f740/GenerateCLP/GenerateCLPLauncher.c.in#L19

SlicerExecutionModel (specifically the GenerateCLPLauncher) will not compile with ITK master.

### PR DESCRIPTION
**Pull request by dzenanz**
Closes #138.

### CODE REVIEW

**Review by sjh26 — APPROVED** [review]
lgtm!

**Comment by dzenanz** [comment]
The CI seems to be broken. The tests succeed on both my local Linux and Windows machines. Should we merge this, or wait for someone to fix the CI and rebase?

**Review by aylward — APPROVED** [review]
Nice!

Failing test seems to be an authentication issue (requesting write access to this repo during testing - weird).  I've tested this on my laptop: Windows and Linux.  Works great on my custom (non-Slicer) apps that use SlicerExecutionModel for CLI parsing.

**Comment by hjmjohnson** [comment]
@dzenanz THANK YOU!

**Pull request merged**
