### PR TITLE
2979 support for cli point coordinate system files

### PR DESCRIPTION
**Pull request by naucoin**
2015 Summer Project Week project, added support for passing fiducials as point files to CLIs.

### CODE REVIEW

**Comment by pieper** [comment]
Hi Nicole - let's discuss this on the developer hangout today.  Looks good to me so if you have no outstanding concerns I'd say let's integrate this.

**Comment by naucoin** [comment]
No outstanding concerns on my part, we didn't really have a quorum on that tcon though, want me to add it to the agenda for the next one?

**Comment by pieper** [comment]
I'd say go ahead and merge - this is a good improvement and since we're not (yet) in a release cycle feature commits are welcome.

**Comment by naucoin** [comment]
Do I have write access to this Slicer sub project? And does it only have a github repository, no SVN?

**Comment by pieper** [comment]
Looks like a smaller group on this one.  @hjmjohnson @millerjv @finetjul  or @jcfr will need to merge according to the current settings.

**Comment by naucoin** [comment]
Okay, will monitor and ping again if there's a delay.

**Comment by jcfr** [comment]
@naucoin  I will take care of this today. Thanks for the patches. 

Do we need to integrate patches on the Slicer side too ?

**Comment by naucoin** [comment]
We do, I'm getting that pull request together now (merging two commits, rebasing).

**Comment by hjmjohnson** [comment]
@jcfr I had already tested build against BRAINSTools, and then merged before I saw your messages.

**Comment by jcfr** [comment]
@hjmjohnson Great. Thanks again for testing and integrating :+1:

**Comment by naucoin** [comment]
Slicer pull request: https://github.com/Slicer/Slicer/pull/307

**Pull request merged**
