### PR TITLE
COMP: Fix language feature introspection for SEM

### PR DESCRIPTION
**Pull request by hjmjohnson**
Configuring with clang version 6.0.0 would fail with
error message:

CMake Error at (target_compile_features):
  target_compile_features no known features for CXX compiler

  "Clang"

  version 6.0.0.

This is related to reported issues, and suggested solution in:

https://gitlab.kitware.com/cmake/cmake/issues/17712
https://gitlab.kitware.com/cmake/cmake/issues/17714

The canonical top-level CMakeLists.txt file should be:

cmake_minimum_required(VERSION 3.10) # or some other version
project(MyProject) # optionally list languages or use NONE to suppress them

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks Hans, I will review and integrate in the next few days. Thanks for your patience.

**Comment by hjmjohnson** [comment]
A new important warning is now present regarding g use of deprecated CMake features.   This allows building with modern CMake, c++, ITK versions,   But the (add_exports ??? ) option still needs updating

**Comment by hjmjohnson** [comment]
@jcfr Could you please have a look at this PR?

**Comment by jcfr** [comment]
> @jcfr Could you please have a look at this PR?

I fixed and improved the testing infrastructure and rebased this topic.

**Pull request merged**
