### PR TITLE
ENH: Add Docker Test file

### PR DESCRIPTION
**Pull request by LucasGandel**
This commit add a Docker file allowing to easily build
and test the project. It contains the recipe allowing to
build ITK so that SlicerExecutionModel can quickly be
configured, built and tested.

This PR reorganize part of #46 to only include docker changes

### CODE REVIEW

**Comment by LucasGandel** [comment]
Cc: @jcfr  @thewtex

**Comment by thewtex** [comment]
:+1:  LGTM!

**Comment by jcfr** [comment]
After discussing with @LucasGandel , he will improve a little bit more doing:

## Step 1
* Updating the docker file to first use `v4.8.1`
* Confirm the test pass using that version. He will install docker on his machine.
* We will integrate the request as soon as this is confirmed

## Step 2
* Provide a circleCI file testing with  `v4.8.1`
* Test are expected to pass

## Step 3
* Update docker + circle ci to use latest ITK
* Test are expected to fail 

## Step 4
* Integrate fix for ITKExpat issue



## Other ideas:

Test SlicerExecutionModel simultaneously against ITK `v.4.8.1`, ITK latest, ...

* Reorganize the docker scripts and docker files like this:
```
test/DockerFile-ITK-v4.8.1/DockerFile
test/DockerFile-ITK-v4.9.0/DockerFile
test/DockerFile/DockerFile
test/DockerScripts/build.sh
test/DockerScripts/run.sh
test/DockerScripts/test.sh
```

* That would allow to have a Docker contained for each version of ITK leveraging DockerHub automated build for `master` branch specifying folder `test/DockerFile-ITK-v4.8.1`, `test/DockerFile-ITK-v4.9.0`, .. and associating tags like `ITK-v4.8.1`. That way, a container specific to each ITK version could be pull using something like `docker pull Slicer/SlicerExecutionModel:ITK-v4.8.1`.

* What I am struggling with is how to leverage the different containers within on `circleci.yml` so that each SlicerExecutionModel PR is built against all version of ITK. Within Travis-ci, I guess the solution would be to have a build matrix and pulling the different container, building and running test test.

**Comment by thewtex** [comment]
Sounds like a good plan :-)

To test against multiple versions, just add additional 'pull' and 'test.sh' lines to the circle.yml.  Each line will be similar, but use different docker tags. There is a little more duplication than a Travis-CI build matrix, but it will do the job in this case.  I don't know how much Travis-CI has rolled out Docker support to be used by tests -- if it is available, that could be used, too.

**Pull request merged**
