### PR TITLE
Wip test hack

### PR DESCRIPTION
**Pull request by hjmjohnson**

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks 👍 

I should be able to test this tomorrow morning.

**Comment by hjmjohnson** [comment]
@jcfr See #127 for the non-wip version reaady for commit.

**Comment by hjmjohnson** [comment]
> Thanks 👍
> 
> I should be able to test this tomorrow morning.

Can we merge #127 so that we can test and merge #126?

**Comment by hjmjohnson** [comment]
@jcfr The docker image still needs to be updated.

**Comment by jcfr** [comment]
> The docker image still needs to be updated.

Thanks for the ping and thanks for your patience :pray: 

This past few days have been crazy and I missed this.

**Comment by hjmjohnson** [comment]
This is now duplicated. See #129

**Pull request closed without merging**
